name: live_chat_app
description: Flutter sample live chat

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  firebase_core: ^2.22.0
  flutter_svg: 
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  build_runner: ^2.3.3
  cloud_firestore: ^4.13.1
  json_serializable: ^6.6.2
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  curved_progress_bar: ^1.0.2
  firebase_storage: ^11.5.1
  toast: ^0.3.0
  firebase_messaging: ^14.7.4
  intl: ^0.18.1
  flutter_slidable: ^3.0.1
  image_picker: ^1.0.4
  image_cropper: ^4.0.1
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.2.3
  badges: ^3.1.1
  skeleton_text: ^3.0.1
  uuid: ^4.1.0
  file: ^6.1.4
  hive: ^2.2.3
  path_provider: ^2.1.1
  rflutter_alert: ^2.0.7
  google_fonts: ^4.0.4
  flutter_math_fork: ^0.5.0
  flutter_tex: ^4.0.3+4
  connectivity_plus: ^2.1.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  mobile_scanner: ^3.5.5
  blurrycontainer: ^1.0.2
  flutter_launcher_icons: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter_icons:
  image_path: "assets/images/mutiara_cosmetics.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/