name: live_chat_app
description: Flutter sample live chat

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  firebase_core: ^2.22.0
  flutter_svg: ^2.0.5
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  build_runner: ^2.3.3
  cloud_firestore: ^4.13.1
  json_serializable: ^6.6.2
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  curved_progress_bar: ^1.0.2
  firebase_storage: ^11.5.1
  toast: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/